# Where things are
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir:    ./_data
collections: null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'README.md', 'Rakefile', 'Procfile.dev', 'unicorn-dev.rb', 'LICENSE', 'CNAME', 'node_modules', 'package.json', 'package-lock.json', 'vite.config.js', 'docs']
keep_files:   [".git", ".svn"]
encoding:     "utf-8"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/vite

# Conversion
markdown:     kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
url:     http://velocitylabs.io

# Outputting
permalink:     /blog/:year/:month/:day/:title/
paginate_path: /blog/:num
paginate:      10
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge

minfy_html: true

## Company ##
company:
  address:
    street:    "221 E. Indianola Ave."
    city:      Phoenix
    state:     AZ
    zip:       85012
  description: Velocity Labs is a Ruby on Rails and JavaScript development company. We specialize in custom web application development projects.
  social:
    github:    velocity-labs
    twitter:   velocitylabs
  logo:        logo-text.png
  name:        Velocity Labs
  phone:       (602) 633-5049
  subtitle:    Ruby on Rails Developers | Custom Web Applications

## reCAPTCHA ##
recaptcha_v3_site_key: "6LcU23YsAAAAACwid6UHIKhccHDQBIEjzN2TIbkR"

## Blog ##
blog:
  title:    The Lab Notebook
  subtitle: "brought to you by <a href=\"http://velocitylabs.io/\">Velocity Labs</a>"
